defmodule Spotter.Repo.Migrations.AddSubagentIdToMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :subagent_id,
          references(:subagents, column: :id, name: "messages_subagent_id_fkey", type: :uuid)
    end
  end

  def down do
    alter table(:messages) do
      remove :subagent_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `messages` table without the `messages_subagent_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end