defmodule Spotter.Repo.Migrations.AddIsMetaToMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :is_meta, :boolean
    end
  end

  def down do
    alter table(:messages) do
      remove :is_meta
    end
  end
end