defmodule Spotter.Repo.Migrations.AddRawPayloadAndSubagentType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add(:raw_payload, :map)
    end

    alter table(:subagents) do
      add(:subagent_type, :text)
    end
  end

  def down do
    alter table(:subagents) do
      remove(:subagent_type)
    end

    alter table(:messages) do
      remove(:raw_payload)
    end
  end
end
