defmodule Spotter.Repo.Migrations.AddAggregateWatermarksToProjectIngestStates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:project_ingest_states) do
      add(:heatmap_last_run_at, :utc_datetime_usec)
      add(:heatmap_window_days, :bigint, null: false, default: 30)
      add(:co_change_last_run_at, :utc_datetime_usec)
      add(:co_change_window_days, :bigint, null: false, default: 30)
    end
  end

  def down do
    alter table(:project_ingest_states) do
      remove(:co_change_window_days)
      remove(:co_change_last_run_at)
      remove(:heatmap_window_days)
      remove(:heatmap_last_run_at)
    end
  end
end
