defmodule Spotter.Repo.Migrations.AddSessionReworks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:session_reworks, primary_key: false) do
      add :session_id,
          references(:sessions,
            column: :id,
            name: "session_reworks_session_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :detection_source, :text, null: false
      add :event_timestamp, :utc_datetime_usec
      add :first_tool_use_id, :text, null: false
      add :occurrence_index, :bigint, null: false
      add :relative_path, :text
      add :file_path, :text, null: false
      add :tool_use_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:session_reworks, [:session_id, :tool_use_id],
             name: "session_reworks_unique_session_tool_use_index"
           )
  end

  def down do
    drop_if_exists unique_index(:session_reworks, [:session_id, :tool_use_id],
                     name: "session_reworks_unique_session_tool_use_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `session_reworks` table without the `session_reworks_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:session_reworks)
  end
end