defmodule Spotter.Repo.Migrations.AddSessionIngestFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      add(:ingest_status, :text)
      add(:ingest_warning_count, :bigint, null: false, default: 0)
      add(:ingest_error_count, :bigint, null: false, default: 0)
      add(:ingest_report, :map)
    end
  end

  def down do
    alter table(:sessions) do
      remove(:ingest_report)
      remove(:ingest_error_count)
      remove(:ingest_warning_count)
      remove(:ingest_status)
    end
  end
end
