defmodule Spotter.Repo.Migrations.AddToolCalls do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tool_calls, primary_key: false) do
      add :session_id,
          references(:sessions, column: :id, name: "tool_calls_session_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :error_content, :text
      add :is_error, :boolean, null: false
      add :tool_name, :text, null: false
      add :tool_use_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:tool_calls, [:tool_use_id], name: "tool_calls_unique_tool_use_id_index")
  end

  def down do
    drop_if_exists unique_index(:tool_calls, [:tool_use_id],
                     name: "tool_calls_unique_tool_use_id_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `tool_calls` table without the `tool_calls_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:tool_calls)
  end
end