defmodule Spotter.Repo.Migrations.AddSizeBytesLocToFileHeatmaps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:file_heatmaps) do
      add :size_bytes, :bigint
      add :loc, :bigint
    end
  end

  def down do
    alter table(:file_heatmaps) do
      remove :loc
      remove :size_bytes
    end
  end
end