defmodule Spotter.Repo.Migrations.AddSubagentUpsert do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:tool_call_runs) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :error_content
    # end
    # 
    # alter table(:messages) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :model
    # 
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :cache_creation_input_tokens
    # 
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :cache_read_input_tokens
    # 
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :output_tokens
    # 
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :input_tokens
    # end
    # 
  end

  def down do
    # alter table(:messages) do
    # This is the `down` migration of the statement:
    #
    #     remove :input_tokens
    #
    # 
    # add :input_tokens, :bigint
    # This is the `down` migration of the statement:
    #
    #     remove :output_tokens
    #
    # 
    # add :output_tokens, :bigint
    # This is the `down` migration of the statement:
    #
    #     remove :cache_read_input_tokens
    #
    # 
    # add :cache_read_input_tokens, :bigint
    # This is the `down` migration of the statement:
    #
    #     remove :cache_creation_input_tokens
    #
    # 
    # add :cache_creation_input_tokens, :bigint
    # This is the `down` migration of the statement:
    #
    #     remove :model
    #
    # 
    # add :model, :text
    # end
    # 
    # alter table(:tool_call_runs) do
    # This is the `down` migration of the statement:
    #
    #     remove :error_content
    #
    # 
    # add :error_content, :text
    # end
    # 
  end
end