defmodule Spotter.Repo.Migrations.AddToolCallRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tool_call_runs, primary_key: false) do
      add :project_id,
          references(:projects, column: :id, name: "tool_call_runs_project_id_fkey", type: :uuid),
          null: false

      add :session_id,
          references(:sessions, column: :id, name: "tool_call_runs_session_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :canonical_cwd, :text
      add :worktree_name, :text
      add :parent_tool_use_id, :text
      add :subagent_id, :text
      add :agent_id, :text
      add :source_scope, :text
      add :end_ordinal, :bigint
      add :start_ordinal, :bigint
      add :duration_source, :text
      add :duration_ms, :bigint
      add :finished_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec
      add :status, :text, null: false
      add :input_summary, :text
      add :command_fingerprint, :text
      add :command, :text
      add :tool_name, :text, null: false
      add :tool_use_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:tool_call_runs, [:tool_use_id],
             name: "tool_call_runs_unique_tool_use_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:tool_call_runs, [:tool_use_id],
                     name: "tool_call_runs_unique_tool_use_id_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `tool_call_runs` table without the `tool_call_runs_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `tool_call_runs` table without the `tool_call_runs_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:tool_call_runs)
  end
end