defmodule Spotter.Repo.Migrations.AddFileSnapshots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:file_snapshots, primary_key: false) do
      add :session_id,
          references(:sessions, column: :id, name: "file_snapshots_session_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :timestamp, :utc_datetime_usec, null: false
      add :source, :text, null: false
      add :change_type, :text, null: false
      add :content_after, :text
      add :content_before, :text
      add :relative_path, :text
      add :file_path, :text, null: false
      add :tool_use_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `file_snapshots` table without the `file_snapshots_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:file_snapshots)
  end
end