defmodule Spotter.Repo.Migrations.AddErrorContentToToolCallRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Column may already exist from prior uncommitted work; SQLite has no IF NOT EXISTS for ALTER
    case Ecto.Adapters.SQL.query(repo(), "SELECT error_content FROM tool_call_runs LIMIT 0") do
      {:ok, _} -> :ok
      {:error, _} -> execute("ALTER TABLE tool_call_runs ADD COLUMN error_content TEXT")
    end
  end

  def down do
    alter table(:tool_call_runs) do
      remove(:error_content)
    end
  end
end
