defmodule Spotter.Repo.Migrations.UpdateDeps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(
      unique_index(:raw_hook_events, [:hook_event_name, :session_id, :tool_use_id],
        name: "raw_hook_events_unique_event_index"
      )
    )

    create unique_index(:raw_hook_events, [:session_id, :tool_use_id, :hook_event_name],
             name: "raw_hook_events_unique_event_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:raw_hook_events, [:session_id, :tool_use_id, :hook_event_name],
        name: "raw_hook_events_unique_event_index"
      )
    )

    create unique_index(:raw_hook_events, [:hook_event_name, :session_id, :tool_use_id],
             name: "raw_hook_events_unique_event_index"
           )
  end
end
