defmodule Spotter.Repo.Migrations.AddCoChangeGroups do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:co_change_groups, primary_key: false) do
      add :project_id,
          references(:projects,
            column: :id,
            name: "co_change_groups_project_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_seen_at, :utc_datetime_usec
      add :frequency_30d, :bigint, null: false
      add :members, {:array, :text}, null: false, default: []
      add :group_key, :text, null: false
      add :scope, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:co_change_groups, [:project_id, :scope, :group_key],
             name: "co_change_groups_unique_project_scope_group_index"
           )
  end

  def down do
    drop_if_exists unique_index(:co_change_groups, [:project_id, :scope, :group_key],
                     name: "co_change_groups_unique_project_scope_group_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `co_change_groups` table without the `co_change_groups_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:co_change_groups)
  end
end