defmodule Spotter.Repo.Migrations.FixPending do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:messages) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :is_meta
    # end
    # 
  end

  def down do
    # alter table(:messages) do
    # This is the `down` migration of the statement:
    #
    #     remove :is_meta
    #
    # 
    # add :is_meta, :boolean
    # end
    # 
  end
end