defmodule Spotter.Repo.Migrations.AddBeadIdToAnnotations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:annotations) do
      add :bead_id, :text
    end
  end

  def down do
    alter table(:annotations) do
      remove :bead_id
    end
  end
end