defmodule Spotter.Repo.Migrations.RenameHookEndedAtToSessionEndedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:sessions), :hook_ended_at, to: :session_ended_at
  end

  def down do
    rename table(:sessions), :session_ended_at, to: :hook_ended_at
  end
end