defmodule Spotter.Repo.Migrations.AddSessionSlices do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:session_slices, primary_key: false) do
      add :project_id,
          references(:projects, column: :id, name: "session_slices_project_id_fkey", type: :uuid),
          null: false

      add :session_id,
          references(:sessions, column: :id, name: "session_slices_session_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :context_after_lines, :bigint
      add :context_before_lines, :bigint
      add :highlight_tool_use_ids, {:array, :text}, default: []
      add :filters, :map, default: %{}
      add :title, :text
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `session_slices` table without the `session_slices_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `session_slices` table without the `session_slices_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:session_slices)
  end
end