defmodule Spotter.Repo.Migrations.SyncErrorContentSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    columns =
      ~w[input_tokens output_tokens cache_read_input_tokens cache_creation_input_tokens model]

    existing =
      case repo().query("PRAGMA table_info(messages)") do
        {:ok, %{rows: rows}} -> Enum.map(rows, fn [_, name | _] -> name end)
        _ -> []
      end

    for col <- columns, col not in existing do
      type = if col == "model", do: "TEXT", else: "INTEGER"
      execute("ALTER TABLE messages ADD COLUMN #{col} #{type}")
    end
  end

  def down do
    alter table(:messages) do
      remove(:model)
      remove(:cache_creation_input_tokens)
      remove(:cache_read_input_tokens)
      remove(:output_tokens)
      remove(:input_tokens)
    end
  end
end
