defmodule Spotter.Repo.Migrations.AddHiddenAtToSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      add :hidden_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:sessions) do
      remove :hidden_at
    end
  end
end