defmodule Spotter.Repo.Migrations.CreateAnnotations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:annotations, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :comment, :text, null: false
      add :end_col, :bigint, null: false
      add :end_row, :bigint, null: false
      add :start_col, :bigint, null: false
      add :start_row, :bigint, null: false
      add :selected_text, :text, null: false
      add :pane_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:annotations)
  end
end