defmodule Spotter.Repo.Migrations.AddCommitsAndSessionCommitLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:commits, primary_key: false) do
      add(:updated_at, :utc_datetime_usec, null: false)
      add(:inserted_at, :utc_datetime_usec, null: false)
      add(:changed_files, {:array, :text}, null: false, default: [])
      add(:patch_id_stable, :text)
      add(:committed_at, :utc_datetime_usec)
      add(:authored_at, :utc_datetime_usec)
      add(:author_email, :text)
      add(:author_name, :text)
      add(:body, :text)
      add(:subject, :text)
      add(:git_branch, :text)
      add(:parent_hashes, {:array, :text}, null: false, default: [])
      add(:commit_hash, :text, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end

    create table(:session_commit_links, primary_key: false) do
      add(:id, :uuid, null: false, primary_key: true)
      add(:link_type, :text, null: false)
      add(:confidence, :float, null: false)
      add(:evidence, :map)
      add(:inserted_at, :utc_datetime_usec, null: false)
      add(:updated_at, :utc_datetime_usec, null: false)

      add(
        :session_id,
        references(:sessions,
          column: :id,
          name: "session_commit_links_session_id_fkey",
          type: :uuid
        ),
        null: false
      )

      add(
        :commit_id,
        references(:commits,
          column: :id,
          name: "session_commit_links_commit_id_fkey",
          type: :uuid
        ),
        null: false
      )
    end

    create unique_index(:session_commit_links, [:session_id, :commit_id, :link_type],
             name: "session_commit_links_unique_session_commit_link_type_index"
           )

    create unique_index(:commits, [:commit_hash], name: "commits_unique_commit_hash_index")
  end

  def down do
    drop_if_exists(
      unique_index(:commits, [:commit_hash], name: "commits_unique_commit_hash_index")
    )

    drop_if_exists(
      unique_index(:session_commit_links, [:session_id, :commit_id, :link_type],
        name: "session_commit_links_unique_session_commit_link_type_index"
      )
    )

    drop(table(:commits))

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `session_commit_links` table without the `session_commit_links_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `session_commit_links` table without the `session_commit_links_commit_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop(table(:session_commit_links))
  end
end
