defmodule Spotter.Repo.Migrations.AddToolInputToToolCallRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tool_call_runs) do
      add :tool_input, :map
    end
  end

  def down do
    alter table(:tool_call_runs) do
      remove :tool_input
    end
  end
end