defmodule Spotter.Repo.Migrations.AddImageRefToAnnotations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:annotations) do
      add :image_ref, :text
    end
  end

  def down do
    alter table(:annotations) do
      remove :image_ref
    end
  end
end